# Generated by Django 5.2.4 on 2025-07-24 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 20, 22, 3, 416671, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
