# Generated by Django 5.2.8 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('learner', 'Learner'), ('helper', 'Helper')], max_length=20, null=True),
        ),
    ]
