# Generated by Django 5.2.8 on 2026-03-03 15:01

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django.extensions import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_role'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='user',
            name='expert_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
