// app/layout.tsx (server component, default layout entrypoint)
import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "sonner";
import GoogleProvider from "@/providers/GoogleProvider";
import PrelineScriptWrapper from '@/components/PrelineScriptWrapper';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` font-sans antialiased`}>
        <ReduxProvider>
          <QueryProvider>
          <GoogleProvider>
            {children}
            <PrelineScriptWrapper />
            <Toaster/>
            </GoogleProvider>
            </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
