# Generated by Django 5.2.8 on 2026-03-03 15:01

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django.extensions import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='question',
            name='bounty_points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='question',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching for Experts'), ('ongoing', 'Ongoing'), ('answered', 'Answered'), ('closed', 'Closed')], default='searching', max_length=20),
        ),
        migrations.CreateModel(
            name='SolutionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_root_cause', models.TextField(help_text='AI summary of what went wrong')),
                ('solution_steps', models.TextField(help_text='Markdown formatted steps to fix it')),
                ('final_code_snippet', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution_summary', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_invites', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='questions.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('question', 'expert')},
            },
        ),
    ]
