# Generated by Django 5.2.8 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_expert_score_user_profile_embedding'),
        ('questions', '0002_question_bounty_points_question_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='users.tag'),
        ),
    ]
