# Generated by Django 5.2.8 on 2025-11-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('question_asked', 'Question Asked'), ('question_answered', 'Question Answered'), ('message_sent', 'Message Sent'), ('achievement_unlocked', 'Achievement Unlocked'), ('bookmark_added', 'Bookmark Added'), ('upvote_given', 'Upvote Given'), ('helper_joined', 'Helper Joined')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='activities__user_id_a71400_idx'), models.Index(fields=['activity_type', 'created_at'], name='activities__activit_69e45a_idx')],
            },
        ),
    ]
